version: "3.3"

services:

  proxy:
    image: registry1.gesdisc.eosdis.nasa.gov/meditor/meditor_proxy:0.34.0
    ports:
      - "80:8080"
    depends_on:
      - server
      - nats
      - ui
      - database

  notifier:
    image: registry1.gesdisc.eosdis.nasa.gov/meditor/meditor_notifier:0.37.0
    depends_on:
      - nats

  ui:
    image: registry1.gesdisc.eosfdis.nasa.gov/meditor/meditor_ui:0.61.0
    
  server:
    image: registry1.gesdisc.eosdis.nasa.gov/meditor/meditor_server:0.54.0
    depends_on:
      - database
      - nats

  database:
    image: registry1.gesdisc.eosdis.nasa.gov/certified/mongo:4.1.4

  nats:
    image: nats-streaming:0.15.1

  monitor:
    image: portainer/portainer:1.20.0
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - monitor_data:/data

  agent:
    image: portainer/agent:1.1.2
    environment:
      AGENT_CLUSTER_ADDR: tasks.agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    ports:
      - "9001:9001"

volumes:
  monitor_data:

networks:
  default:
    driver: bridge
