version: "3.3"

services:
  
  ui:
    container_name: meditor_ui
    build: ui
    env_file:
      - .env
    ports:
      - "${UI_HOST_PORT}:4200"
    volumes:
      - ${UI_HOST_VOLUME}:/usr/src/app
      - /usr/src/app/node_modules
  
  server:
    container_name: meditor_server
    build: nodejs-server-server
    restart: always
    env_file:
      - .env
    ports:
      - "${SERVER_HOST_PORT}:8081"
    volumes:
      - ${SERVER_HOST_VOLUME}:/usr/src/app
      - /usr/src/app/node_modules
    links:
      - database
    depends_on:
      - database

  database:
    container_name: meditor_database
    image: registry1.gesdisc.eosdis.nasa.gov/certified/mongo:4.1.4
    volumes:
      - ${DATABASE_HOST_VOLUME}:/data/db
    command: mongod --port ${DATABASE_HOST_PORT}
    ports:
      - "${DATABASE_HOST_PORT}:${DATABASE_HOST_PORT}"

  database-seed:
    container_name: meditor_database_seed
    build: mongo-seed/.
    links:
      - database
