version: "3.3"

services:

  status:
    container_name: meditor_status
    image: dev.gesdisc.eosdis.nasa.gov:443/meditor_status:0.18.0
    environment:
      - APP_URL=${APP_URL}
      - APP_UI_URL=${APP_UI_URL}
      - MONGOURL=mongodb://meditor_database:27017,meditor_database_sec_1:27017,meditor_database_sec_2:27017/?replicaSet=meditor

  proxy:
    container_name: meditor_proxy
    image: dev.gesdisc.eosdis.nasa.gov:443/meditor_proxy:0.18.0
    restart: on-failure
    ports:
      - "80:8080"
    depends_on:
      - database

  notifier:
    container_name: meditor_notifier
    image: dev.gesdisc.eosdis.nasa.gov:443/meditor_notifier:0.18.0
    restart: on-failure
    depends_on:
      - database
    environment:
      - MONGOURL=mongodb://meditor_database:27017,meditor_database_sec_1:27017,meditor_database_sec_2:27017/?replicaSet=meditor

  ui:
    container_name: meditor_ui
    image: dev.gesdisc.eosdis.nasa.gov:443/meditor_ui:0.18.0
    restart: on-failure
    environment:
      - NODE_ENV=${NODE_ENV}
      - APP_URL=${APP_URL}
      - APP_UI_URL=${APP_UI_URL}
 
  server:
    container_name: meditor_server
    image: dev.gesdisc.eosdis.nasa.gov:443/meditor_server:0.18.0
    depends_on:
      - database
    restart: on-failure
    environment:
      - NODE_ENV=${NODE_ENV}
      - APP_URL=${APP_URL}
      - APP_UI_URL=${APP_UI_URL}
      - MONGOURL=mongodb://meditor_database:27017,meditor_database_sec_1:27017,meditor_database_sec_2:27017/?replicaSet=meditor
    secrets:
      - auth_host
      - auth_client_id
      - auth_client_secret

  database:
    container_name: meditor_database
    image: dev.gesdisc.eosdis.nasa.gov:443/mongo/4.1.4
    restart: on-failure
    ports:
      - "47017:27017"
    volumes:
      - ${PWD}/mongo-replicaset/mongorc.js:/etc/mongorc.js
    command: --replSet meditor

  database_sec_1:
    container_name: meditor_database_sec_1
    image: dev.gesdisc.eosdis.nasa.gov:443/mongo/4.1.4
    restart: on-failure
    depends_on:
      - database
    ports:
      - "47018:27017"
    volumes:
      - ${PWD}/mongo-replicaset/mongorc.js:/etc/mongorc.js
    command: --replSet meditor

  database_sec_2:
    container_name: meditor_database_sec_2
    image: dev.gesdisc.eosdis.nasa.gov:443/mongo/4.1.4
    restart: on-failure
    depends_on:
      - database
    ports:
      - "47019:27017"
    volumes:
      - ${PWD}/mongo-replicaset/mongorc.js:/etc/mongorc.js
    command: --replSet meditor
    
  database-replicaset:
    container_name: meditor_replicaset
    image: dev.gesdisc.eosdis.nasa.gov:443/meditor_replicaset:0.18.0
    restart: on-failure
    depends_on:
      - database
      - database_sec_1
      - database_sec_2

secrets:
    auth_host:
      external: true
    auth_client_id:
      external: true
    auth_client_secret:
      external: true
