version: "3.3"

services:

  proxy:
    container_name: meditor_proxy
    image: dev.gesdisc.eosdis.nasa.gov:443/meditor_proxy:0.5.0
    ports:
      - "80:8080"
    links:
      - ui
      - server
    depends_on:
      - database

  notifier:
    container_name: meditor_notifier
    image: dev.gesdisc.eosdis.nasa.gov:443/meditor_notifier:0.5.0
    links:
      - database
    depends_on:
      - database
    environment:
      - MONGOURL=mongodb://meditor_database:27017/

  ui:
    container_name: meditor_ui
    image: dev.gesdisc.eosdis.nasa.gov:443/meditor_ui:0.5.0
    environment:
      - NODE_ENV=${NODE_ENV}
      - APP_URL=${APP_URL}
      - APP_UI_URL=${APP_UI_URL}
 
  server:
    container_name: meditor_server
    image: dev.gesdisc.eosdis.nasa.gov:443/meditor_server:0.5.0
    links:
      - database
    depends_on:
      - database
    environment:
      - APP_URL=${APP_URL}
      - APP_UI_URL=${APP_UI_URL}
      - AUTH_HOST=${AUTH_HOST}
      - AUTH_CLIENT_ID=${AUTH_CLIENT_ID}
      - AUTH_CLIENT_SECRET=${AUTH_CLIENT_SECRET}
      - MONGOURL=mongodb://meditor_database:27017/

  database:
    container_name: meditor_database
    image: mongo:4.1
    ports:
      - "27017:27017"
  