version: "3.3"

services:

  proxy:
    image: registry1.gesdisc.eosdis.nasa.gov/meditor/meditor_proxy:0.31.0
    restart: on-failure
    ports:
      - "81:8080"
    depends_on:
      - database
    environment:
      - SERVER_HOST=meditor_test_server
      - UI_HOST=meditor_test_ui
      - MONITOR_HOST=lb.gesdisc.eosdis.nasa.gov   # use the same monitor as LB
    deploy:
      placement:
        constraints:
          - node.labels.database == primary

  ui:
    image: registry1.gesdisc.eosdis.nasa.gov/meditor/meditor_ui:0.47.0
    restart: on-failure
    environment:
      - NODE_ENV=${NODE_ENV}
      - APP_URL=https://uat.gesdisc.eosdis.nasa.gov
      - APP_UI_URL=https://uat.gesdisc.eosdis.nasa.gov/meditor
    deploy:
      placement:
        constraints:
          - node.labels.database == primary

  server:
    image: registry1.gesdisc.eosdis.nasa.gov/meditor/meditor_server:0.42.0
    depends_on:
      - database
    restart: on-failure
    environment:
      - NODE_ENV=${NODE_ENV}
      - NODE_OPTIONS=--max_old_space_size=4096
      - APP_URL=https://uat.gesdisc.eosdis.nasa.gov
      - APP_UI_URL=https://uat.gesdisc.eosdis.nasa.gov/meditor
      - MONGOURL=mongodb://meditor_test_database:27017
    secrets:
      - auth_host
      - auth_client_id
      - auth_client_secret
    deploy:
      placement:
        constraints:
          - node.labels.database == primary

  nats:
    container_name: nats
    image: nats-streaming:0.15.1 
    restart: on-failure
    ports:
      - "${NATS_HOST_PORT}:4222"
      - "${NATS_MONITORING_PORT}:8222"
    volumes:
      - ${NATS_HOST_VOLUME}:/nats/data

  database:
    image: registry1.gesdisc.eosdis.nasa.gov/certified/mongo:4.1.4
    restart: on-failure
    ports:
      - "47018:27017"
    volumes:
      - ${DATABASE_HOST_VOLUME}:/data/db
    deploy:
      placement:
        constraints:
          - node.labels.database == primary

secrets:
    auth_host:
      external: true
    auth_client_id:
      external: true
    auth_client_secret:
      external: true
