version: "3.3"

services:

  proxy:
    container_name: meditor_proxy
    image: dev.gesdisc.eosdis.nasa.gov:443/meditor_proxy
    ports:
      - "80:8080"
    links:
      - ui
      - server
    depends_on:
      - database

  notifier:
    container_name: meditor_notifier
    image: dev.gesdisc.eosdis.nasa.gov:443/meditor_notifier
    links:
      - database
    depends_on:
      - database
    environment:
      - MONGOURL=mongodb://meditor_database:27017/

  ui:
    container_name: meditor_ui
    image: dev.gesdisc.eosdis.nasa.gov:443/meditor_ui
    environment:
      - NODE_ENV=${NODE_ENV}
      - APP_URL=${APP_URL}
      - APP_UI_URL=${APP_UI_URL}
 
  server:
    container_name: meditor_server
    image: dev.gesdisc.eosdis.nasa.gov:443/meditor_server
    links:
      - database
    depends_on:
      - database
    environment:
      - APP_URL=${APP_URL}
      - APP_UI_URL=${APP_UI_URL}
      - AUTH_HOST=${AUTH_HOST}
      - AUTH_CLIENT_ID=${AUTH_CLIENT_ID}
      - AUTH_CLIENT_SECRET=${AUTH_CLIENT_SECRET}
      - MONGOURL=mongodb://meditor_database:27017/

  database:
    container_name: meditor_database
    image: mongo:latest
    restart: always
    ports:
      - "47017:27017"
    command: --smallfiles --replSet meditor

  database-sec-1:
    container_name: meditor_database_sec_1
    image: mongo:latest
    restart: always
    ports:
      - "47018:27017"
    command: --smallfiles --replSet meditor

  database-sec-2:
    container_name: meditor_database_sec_2
    image: mongo:latest
    restart: always
    ports:
      - "47019:27017"
    command: --smallfiles --replSet meditor

  database-replicaset:
    container_name: meditor_replicaset
    image: dev.gesdisc.eosdis.nasa.gov:443/meditor_replicaset
    links:
      - database
      - database-sec-1
      - database-sec-2
