version: "3.3"

services:

  proxy:
    ports:
      - "80:8080"
    depends_on:
      - server
      - nats
      - ui
      - database

  notifier:
    depends_on:
      - nats

  ui:
    depends_on:
      - server
    
  server:
    depends_on:
      - database
      - nats

  database:
    image: ${REGISTRY}mongo:4.1.4

  nats:
    image: ${REGISTRY}nats-streaming:0.15.1

  monitor:
    image: ${REGISTRY}portainer/portainer:1.20.0
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - monitor_data:/data

  agent:
    image: ${REGISTRY}portainer/agent:1.1.2
    environment:
      AGENT_CLUSTER_ADDR: tasks.agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    ports:
      - "9001:9001"

volumes:
  monitor_data:

networks:
  default:
    driver: bridge
