openapi: 3.1.0
servers:
    - url: http://localhost/meditor/api
      description: Local Server
info:
    description: |
        This is mEditor's API documentation. You can execute live requests against the server and read how to use the API.

        ## OpenAPI Specification
        This API is documented in **OpenAPI format**.

        ## Cross-Origin Resource Sharing
        This API features Cross-Origin Resource Sharing (CORS) implemented in compliance with  [W3C spec](https://www.w3.org/TR/cors/).
        And that allows cross-domain communication from the browser.
        All responses have a wildcard same-origin which makes them completely public and accessible to everyone, including any code on any site.

        ## Authentication

    version: 2.0.0
    title: mEditor API Yaml
paths:
    /models:
        get:
            tags:
                - models
            summary: get all models
            description: Get a list of all models.
            operationId: getModels
            responses:
                - '200'
            x-codeSamples:
