name: Continuous Integration

# This action works with pull requests and pushes to branches other than main
on:
  pull_request:
  push:
    branches-ignore:
      - main

jobs:
  app-jest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest code from branch
        uses: actions/checkout@v3
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}
          # This is important to fetch the changes to the previous commit
          fetch-depth: 0

      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: packages/app/node_modules
          # cache is reset if any new dependencies are installed
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install package dependencies (package.json)
        working-directory: ./packages/app
        # don't install if we can reuse the cached node_modules
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        run: npm ci

      - name: Run tests
        working-directory: ./packages/app
        run: npm run test
